name: cortex_mlops
channels:
  - apple
  - conda-forge
dependencies:
    - python=3.9
    - pip>=19.0
    - tensorflow-deps=2.10.0
    - grpcio=1.44.0
    - pip:
        - tensorflow-macos==2.11.0
        - tensorflow-metal==0.7.0
        - poetry==1.3.2
        - grpcio-tools==1.44.0
